/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    TodoBody: typeof import('./src/components/TodoBody.vue')['default']
    TodoHeader: typeof import('./src/components/TodoHeader.vue')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
  }
}
